# Jussi's kakrc

## Prefs and binds
set-option global makecmd 'make -j8'
set-option global grepcmd 'rg --column --with-filename'

map -docstring 'Open new' global normal <c-w> ': new<ret>'

## Plugin setup

# Load plug.kak to manage plugins.
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

# Language server protocol support
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# Golang
plug "chriswalker/golang.kak"

## Custom commands
define-command -params 1 -shell-script-candidates %{ git ls-tree -r HEAD --name-only } gf %{ edit %arg{1} }
